version: '3.8'
services:
  markdown-editor-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    command: yarn start:dev  
